<div style ="background-color :LIGHTBLUE; color:#145A32;padding:15px;border-radius:10px;text-align:center;font-size:20px;"><b>DATA PREPROCESSING PROJECT</b></div>

This project demonstrates data preprocessing techniques using Python and Pandas.

Steps performed:
1. Data Loading
2. Data Inspection
3. Handling Missing Values
4. Removing Duplicates
5. Feature Encoding
6. Data Standardization

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>IMPORT LIBRARIES</b>
</div>

In [3]:

import pandas as pd
import numpy as np

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>LOAD DATASET</b>
</div>

In [4]:
df = pd.read_csv("Students Social Media Addiction.csv")

print("Dataset Loaded Successfully")
df.head()

Dataset Loaded Successfully

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,Female,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,Male,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,Female,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,Male,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,Male,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>UNDERSTANING THE DATA</b>
</div>

In [5]:
df.tail(2)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
703,704,24,Male,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,Female,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 705 entries, 0 to 704
Data columns (total 13 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Student_ID                    705 non-null    int64
 1   Age                           705 non-null    int64
 2   Gender                        705 non-null    str
 3   Academic_Level                705 non-null    str
 4   Country                       705 non-null    str
 5   Avg_Daily_Usage_Hours         705 non-null    float64
 6   Most_Used_Platform            705 non-null    str
 7   Affects_Academic_Performance  705 non-null    str
 8   Sleep_Hours_Per_Night         705 non-null    float64
 9   Mental_Health_Score           705 non-null    int64
 10  Relationship_Status           705 non-null    str
 11  Conflicts_Over_Social_Media   705 non-null    int64
 12  Addicted_Score                705 non-null    int64
dtypes: float64(2), int64(5), str(6)
memory usage: 71.7 KB

In [7]:
df.columns

Index(['Student_ID', 'Age', 'Gender', 'Academic_Level', 'Country',
       'Avg_Daily_Usage_Hours', 'Most_Used_Platform',
       'Affects_Academic_Performance', 'Sleep_Hours_Per_Night',
       'Mental_Health_Score', 'Relationship_Status',
       'Conflicts_Over_Social_Media', 'Addicted_Score'],
      dtype='str')

In [8]:
df.dtypes

Student_ID                        int64
Age                               int64
Gender                              str
Academic_Level                      str
Country                             str
Avg_Daily_Usage_Hours           float64
Most_Used_Platform                  str
Affects_Academic_Performance        str
Sleep_Hours_Per_Night           float64
Mental_Health_Score               int64
Relationship_Status                 str
Conflicts_Over_Social_Media       int64
Addicted_Score                    int64
dtype: object

In [9]:
df.shape

(705, 13)

In [10]:
df.describe()

,Student_ID,Age,Avg_Daily_Usage_Hours,Sleep_Hours_Per_Night,Mental_Health_Score,Conflicts_Over_Social_Media,Addicted_Score
count,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000,705.000000
mean,353.000000,20.659574,4.918723,6.868936,6.226950,2.849645,6.436879
std,203.660256,1.399217,1.257395,1.126848,1.105055,0.957968,1.587165
min,1.000000,18.000000,1.500000,3.800000,4.000000,0.000000,2.000000
25%,177.000000,19.000000,4.100000,6.000000,5.000000,2.000000,5.000000
50%,353.000000,21.000000,4.800000,6.900000,6.000000,3.000000,7.000000
75%,529.000000,22.000000,5.800000,7.700000,7.000000,4.000000,8.000000
max,705.000000,24.000000,8.500000,9.600000,9.000000,5.000000,9.000000

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>MISSING VALUE ANALYSIS</b>
</div>

In [12]:
df.isnull()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,False,False,False,False,False,False,False,False,False,False,False,False,False
701,False,False,False,False,False,False,False,False,False,False,False,False,False
702,False,False,False,False,False,False,False,False,False,False,False,False,False
703,False,False,False,False,False,False,False,False,False,False,False,False,False
704,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
df.isnull().sum()

Student_ID                      0
Age                             0
Gender                          0
Academic_Level                  0
Country                         0
Avg_Daily_Usage_Hours           0
Most_Used_Platform              0
Affects_Academic_Performance    0
Sleep_Hours_Per_Night           0
Mental_Health_Score             0
Relationship_Status             0
Conflicts_Over_Social_Media     0
Addicted_Score                  0
dtype: int64

In [14]:
df.isnull().sum().sum()

np.int64(0)

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>HANDLEING MISSING VALUES</b>
</div>

In [26]:
df.fillna(df.mean(numeric_only=True), inplace=True)

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,0,Undergraduate,Bangladesh,5.2,Instagram,Yes,6.5,6,In Relationship,3,8
1,2,22,1,Graduate,India,2.1,Twitter,No,7.5,8,Single,0,3
2,3,20,0,Undergraduate,USA,6.0,TikTok,Yes,5.0,5,Complicated,4,9
3,4,18,1,High School,UK,3.0,YouTube,No,7.0,7,Single,1,4
4,5,21,1,Graduate,Canada,4.5,Facebook,Yes,6.0,6,In Relationship,2,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...
700,701,20,0,Undergraduate,Italy,4.7,TikTok,No,7.2,7,In Relationship,2,5
701,702,23,1,Graduate,Russia,6.8,Instagram,Yes,5.9,4,Single,5,9
702,703,21,0,Undergraduate,China,5.6,WeChat,Yes,6.7,6,In Relationship,3,7
703,704,24,1,Graduate,Japan,4.3,Twitter,No,7.5,8,Single,2,4
704,705,19,0,Undergraduate,Poland,6.2,Facebook,Yes,6.3,5,Single,4,8

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>CHECKING MISSING VALUES</b>
</div>

In [27]:
df.duplicated().sum()

np.int64(0)

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>LABEL ENCODER</b>
</div>

Import LabelEncoder

In [29]:
from sklearn.preprocessing import LabelEncoder

Create Encoder Object

In [30]:
le = LabelEncoder()

Applying Encoding to a Column

In [31]:
df['Gender'] = le.fit_transform(df['Gender'])

Encoding Multiple Columns

In [32]:
categorical_cols = df.select_dtypes(include='object').columns

for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

C:\Users\dhanu\AppData\Local\Temp\ipykernel_22924\1426036719.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = df.select_dtypes(include='object').columns

<div style="background-color:#E8F8F5;color:black;padding:8px;text-align:center;font-size:18px;border-radius:8px;">
<b>DATASET CHECK
</div>

In [33]:
df.head()

,Student_ID,Age,Gender,Academic_Level,Country,Avg_Daily_Usage_Hours,Most_Used_Platform,Affects_Academic_Performance,Sleep_Hours_Per_Night,Mental_Health_Score,Relationship_Status,Conflicts_Over_Social_Media,Addicted_Score
0,1,19,0,2,10,5.2,1,1,6.5,6,1,3,8
1,2,22,1,0,39,2.1,7,0,7.5,8,2,0,3
2,3,20,0,2,102,6.0,6,1,5.0,5,0,4,9
3,4,18,1,1,101,3.0,11,0,7.0,7,2,1,4
4,5,21,1,0,18,4.5,0,1,6.0,6,1,2,7

In [34]:
df.describe

<bound method NDFrame.describe of      Student_ID  Age  Gender  Academic_Level  Country  Avg_Daily_Usage_Hours  \
0             1   19       0               2       10                    5.2
1             2   22       1               0       39                    2.1
2             3   20       0               2      102                    6.0
3             4   18       1               1      101                    3.0
4             5   21       1               0       18                    4.5
..          ...  ...     ...             ...      ...                    ...
700         701   20       0               2       44                    4.7
701         702   23       1               0       82                    6.8
702         703   21       0               2       20                    5.6
703         704   24       1               0       46                    4.3
704         705   19       0               2       78                    6.2

     Most_Used_Platform  Affects_Academic_Performance  Sleep_Hours_Per_Night  \
0                     1                             1                    6.5
1                     7                             0                    7.5
2                     6                             1                    5.0
3                    11                             0                    7.0
4                     0                             1                    6.0
..                  ...                           ...                    ...
700                   6                             0                    7.2
701                   1                             1                    5.9
702                   9                             1                    6.7
703                   7                             0                    7.5
704                   0                             1                    6.3

     Mental_Health_Score  Relationship_Status  Conflicts_Over_Social_Media  \
0                      6                    1                            3
1                      8                    2                            0
2                      5                    0                            4
3                      7                    2                            1
4                      6                    1                            2
..                   ...                  ...                          ...
700                    7                    1                            2
701                    4                    2                            5
702                    6                    1                            3
703                    8                    2                            2
704                    5                    2                            4

     Addicted_Score
0                 8
1                 3
2                 9
3                 4
4                 7
..              ...
700               5
701               9
702               7
703               4
704               8

[705 rows x 13 columns]>

## Conclusion

The dataset was successfully preprocessed by:

• Handling missing values  
• Removing duplicate records  
• Detecting outliers  
• Encoding categorical variables  

The cleaned dataset is now ready for Exploratory Data Analysis (EDA) and Machine Learning.